version: "3.6"
services:
  v2:
    container_name: v2
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        URL: "${PUBLIC_COINOS_URL}"
        BTC: "${PUBLIC_BTC}"
        SOCKET: "${PUBLIC_SOCKET}"
    restart: always
    ports:
      - "3121:3121"
    environment:
      NODE_ENV: production
      ORIGIN: "${ORIGIN}"
      PORT: 3121
      STRIPE: "${STRIPE}"
      LAUNCH: "${LAUNCH}"
    extra_hosts:
      - host.docker.internal:host-gateway
networks:
  default:
    name: net
    external: true
